[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugins-python"

[[redirects]]
  from = "/*"
  to   = "/.netlify/functions/api"
  status = 200
