name: ci
on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install tooling
        run: |
          pip install ruff black pytest


      - name: Lint & format Python
        run: |
          ruff $(git ls-files '*.py') || true
          black --check $(git ls-files '*.py') || true

      - name: Run tests (placeholder)
        run: pytest || true