name: Deploy to VPS
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${VPS_HOST} '
            set -e
            sudo -u www-data git config --global --add safe.directory /srv/emaillm-ws
            cd /srv/emaillm-ws &&
            sudo -u www-data git fetch --all &&
            sudo -u www-data git reset --hard origin/main &&
            sudo systemctl restart emaillm
          '
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
